In [1]:
import numpy as np

In [2]:
zero_x = np.zeros((4,4))
cz = np.eye(4)
h2 = np.ones((4,4))

In [3]:
zero_x[0,1] = 1
zero_x[1,0] = 1
zero_x[2,3] = 1
zero_x[3,2] = 1
zero_x

array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [4]:
cz[3,3] = -1
cz

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [5]:
h2[1,3] = -1
h2[1,1] = -1
h2[2,2] = -1
h2[2,3] = -1
h2[3,1] = -1
h2[3,2] = -1
h2 = (1/(np.sqrt(2))) * h2
h2

array([[ 0.70710678,  0.70710678,  0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678,  0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678, -0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678, -0.70710678,  0.70710678]])

Our U = h2.zero_x.cz.zero_x.h2.zero_x.cz.zero_x

In [6]:
U1 = np.dot(h2, zero_x)
U2 = np.dot(U1, cz)
U3 = np.dot(U2, zero_x)
U4 = np.dot(U3, h2)
U4

array([[ 1., -1.,  1.,  1.],
       [-1.,  1.,  1.,  1.],
       [ 1.,  1.,  1., -1.],
       [ 1.,  1., -1.,  1.]])

In [7]:
input_qubit = (-1) * np.array([[0], [1], [0], [0]])
input_qubit

array([[ 0],
       [-1],
       [ 0],
       [ 0]])

In [8]:
result = np.dot(U4, input_qubit)
result

array([[ 1.],
       [-1.],
       [-1.],
       [-1.]])

In [9]:
x2 = np.zeros((4,4))
x2[0,3] = 1
x2[1,2] = 1
x2[2,1] = 1
x2[3,0] = 1
x2

array([[0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [10]:
U1 = np.dot(h2, x2)
U2 = np.dot(U1, cz)
U3 = np.dot(U2, x2)
U4 = np.dot(U3, h2)
U4

array([[ 1., -1., -1., -1.],
       [-1.,  1., -1., -1.],
       [-1., -1.,  1., -1.],
       [-1., -1., -1.,  1.]])

In [11]:
result = np.dot(U4, input_qubit)
result

array([[ 1.],
       [-1.],
       [ 1.],
       [ 1.]])

In [12]:
def oracle(input_qubit):
    zero_x = np.zeros((4,4))
    cz = np.eye(4)
    cz[3,3] = -1
    zero_x[0,1] = 1
    zero_x[1,0] = 1
    zero_x[2,3] = 1
    zero_x[3,2] = 1
    input_qubit = np.dot(zero_x, input_qubit)
    input_qubit = np.dot(cz, input_qubit)
    input_qubit = np.dot(zero_x, input_qubit)
    return(input_qubit)

In [13]:
def hadamard(input_qubit):
    h2 = np.ones((4,4))
    h2[1,3] = -1
    h2[1,1] = -1
    h2[2,2] = -1
    h2[2,3] = -1
    h2[3,1] = -1
    h2[3,2] = -1
    h2 = (1/(np.sqrt(2))) * h2
    return(np.dot(h2, input_qubit))

In [14]:
def diffuser(input_qubit):
    cz = np.eye(4)
    cz[3,3] = -1
    h2 = np.ones((4,4))
    h2[1,3] = -1
    h2[1,1] = -1
    h2[2,2] = -1
    h2[2,3] = -1
    h2[3,1] = -1
    h2[3,2] = -1
    h2 = (1/(np.sqrt(2))) * h2
    x2 = np.zeros((4,4))
    x2[0,1] = 1
    x2[1,0] = 1
    x2[2,3] = 1
    x2[3,2] = 1
    input_qubit = np.dot(h2, input_qubit)
    input_qubit = np.dot(x2, input_qubit)
    input_qubit = np.dot(cz, input_qubit)
    input_qubit = np.dot(x2, input_qubit)
    input_qubit = np.dot(h2, input_qubit)
    return(input_qubit)

In [15]:
level_1 = hadamard(input_qubit)
level_1

array([[-0.70710678],
       [ 0.70710678],
       [-0.70710678],
       [ 0.70710678]])

In [16]:
level_2 = oracle(level_1)
level_2

array([[-0.70710678],
       [ 0.70710678],
       [ 0.70710678],
       [ 0.70710678]])

In [17]:
output = diffuser(level_2)
output

array([[ 1.11022302e-16],
       [ 2.82842712e+00],
       [-1.11022302e-16],
       [ 1.11022302e-16]])